[package]
name = "section3_oop_design_patterns"
version = "0.1.0"
authors = ["Brendan A R Sechter <b-sechter@unext.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
